In [ ]:
#26 Feb Assignment Solution

In [38]:
#Ans 1:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)
print(type(list_))
print(array_list.dtype)

<class 'list'>
<U1


In [31]:
#Ans 2:
for i in list_:
    print(f"{i} : {type(i)}")
    
for i in array_list:
    print(f"{i} : {i.dtype}")


1 : <class 'str'>
2 : <class 'str'>
3 : <class 'str'>
4 : <class 'str'>
5 : <class 'str'>
1 : <U1
2 : <U1
3 : <U1
4 : <U1
5 : <U1


In [39]:
#Ans 3;
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_, dtype = int)
print(type(list_))
print(array_list.dtype)

for i in list_:
    print(f"{i} : {type(i)}")
    
for i in array_list:
    print(f"{i} : {i.dtype}")


<class 'list'>
int64
1 : <class 'str'>
2 : <class 'str'>
3 : <class 'str'>
4 : <class 'str'>
5 : <class 'str'>
1 : int64
2 : int64
3 : int64
4 : int64
5 : int64


In [44]:
#Ans 4:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

print("Shape:",num_array.shape)
print("Size:",num_array.size)

Shape: (2, 3)
Size: 6


In [4]:
#Ans 5:

import numpy as np
zero_2d_array = np.zeros((3, 3))
print(zero_2d_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
#Ans 6:

import numpy as np
identity_matrix = np.identity(5,dtype="int")
print(identity_matrix)



[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
